### ISSUE TITLE
Create boundary value generators for SQL data types

### ISSUE THREAD

**Issue by mibrahim** [FINRAOS/DataGenerator#247]
Target postgres, oracle & HIVE initially

**Comment by bryantrobbins** [comment]
We could add boundary value support for arbitrary macros.

If a macro is "boundary value aware", it should take a parameter allowing a DG user to specify whether they want positive or negative boundary values at a given point in the model. The macro would then expand into multiple values (rather than a single value, as with our existing macros).

The user would then be able to construct models which take into account positive or negative boundary values at any point. It would be up to the user to construct paths which make logical sense (e.g., which only have one "negative" boundary value per path, if that is a coverage goal).

**Comment by leeny324** [comment]
looking into this. Not #249

**Comment by leeny324** [comment]
start with hive numeric data types and come up with a prototype.

example:
<dg:boundaryPos name="" min="" max="" dataType="" nullable="" dbType=""/>

<dg:boundaryNeg name="" min="" max="" dataType="" nullable="" dbType=""/>

**Comment by bryantrobbins** [comment]
<dg:boundaryPos name="myvar1" dbType="oracle" dataType="VARCHAR(55)">

VS.

<dgBoundaryPos:sql:hive:VARCHAR name="myvar1" length="55">

Some considerations here:
* The more logic we put into a single tag, the slower it will be and more complex it will be to maintain
* Is having a bunch of specific tags more difficult (too difficult) for the end user? SCXML (and maybe and XSD) could assist with dealing with numerous tags.

**Comment by mibrahim** [comment]
Fulfilled by @leeny324 pull request.
